import request from '../utils/https'

export default {
  GetAssetCategoryRecords: params => request.get('/Asset/GetAssetCategoryRecords', params),
  AddAssetCategory: params => request.post('/Asset/AddAssetCategory', params),
  DelAssetCategoryLogic: params => request.post('/Asset/CheckCateDelete', params),
  DelAssetCategory: params => request.post('/Asset/DelAssetCategory', params),
  UpdAssetCategory: params => request.post('/Asset/UpdAssetCategory', params),
  getAssetCategory: params => request.get('/Asset/GetAssetCategory', params),
  getModelCascade: params => request.get('/Asset/GetModelCascade', params),
  getModelCascadeByAuth: params => request.get('/Asset/getModelCascadeByAuth', params),
  getLevelTwoCascade: params => request.get('/Asset/GetLevelTwoCascade', params),
  getAssetModels: params => request.get('/Asset/GetAssetModels', params),
  addAssetModel: params => request.post('/Asset/AddAssetModel', params),
  updAssetModel: params => request.post('/Asset/UpdAssetModel', params),
  delAssetModel: params => request.post('/Asset/DelAssetModel', params),
  getAssetNum: () => request.get('/Asset/GetAssetNum', {}),
  getAssets: params => request.get('/Asset/GetAssets', params),
  addAsset: params => request.post('/Asset/AddAsset', params),
  updAsset: params => request.post('/Asset/UpdAsset', params),
  delAsset: params => request.post('/Asset/DelAsset', params),
  getComponents: params => request.get('/Asset/GetComponents', params),
  addComponent: params => request.post('/Asset/AddComponent', params),
  updComponent: params => request.post('/Asset/UpdComponent', params),
  delComponent: params => request.post('/Asset/DelComponent', params),
  getRepairIssues: params => request.get('/Asset/GetRepairIssues', params),
  addRepairIssue: params => request.post('/Asset/AddRepairIssue', params),
  updRepairIssue: params => request.post('/Asset/UpdRepairIssue', params),
  getNewSerialNo: params => request.get('/Asset/GetNewSerialNo', params),
  getFavoritedFlag: params => request.get('/Asset/GetFavoritedFlag', params),
  getLinkedPart: params => request.get('/Asset/GetLinkedPart', params),
  getComponentsByModel: params => request.get('/Asset/GetComponentsByModel', params),
  getHotWords: params => request.get('/Asset/GetHotKeyWords', params),
  CheckHasModel: params => request.get('/Asset/checkHasModel', params)
}
